Repository LontriTech/terraform-github-repositories, pull requests merged in 2024-09, with the labels that each got.

#134 FIX empty commit breaking workflow terraform-docs
  README.md
Labels: bug, github_actions

#135 OPTIMIZE wf terraform-docs.yml
  .github/workflows/terraform-docs.yml
Labels: enhancement, github_actions

#136 Update LICENSE
  LICENSE
Labels: documentation

#139 Update .gitattributes
  .gitattributes
Labels: enhancement

#138 Update .editorconfig
  .editorconfig
Labels: enhancement

#141 UPDATE .gitignore
  .gitignore
Labels: enhancement
